[package]
name = "parse-project-xml"
version = "0.1.0"
authors = ["Richard Cook <rcook@rcook.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
